import { SDR, Assessor } from './types';

export const INITIAL_SDRS: SDR[] = [
  {
    id: 'sdr-1',
    name: 'Ana Silva',
    agendamentosCount: 25,
    efetivacoesCount: 15,
    metaAgendamentos: 30,
    metaEfetivacaoRate: 50,
    active: true,
    admissionDate: '2024-03-10',
    team: 'Equipe Alpha',
  },
  {
    id: 'sdr-2',
    name: 'Bruno Ramos',
    agendamentosCount: 18,
    efetivacoesCount: 9,
    metaAgendamentos: 20,
    metaEfetivacaoRate: 50,
    active: true,
    admissionDate: '2024-06-15',
    team: 'Equipe Beta',
  },
  {
    id: 'sdr-3',
    name: 'Carlos Oliveira',
    agendamentosCount: 32,
    efetivacoesCount: 24,
    metaAgendamentos: 35,
    metaEfetivacaoRate: 60,
    active: true,
    admissionDate: '2023-11-01',
    team: 'Equipe Alpha',
  },
  {
    id: 'sdr-4',
    name: 'Daniela Costa',
    agendamentosCount: 14,
    efetivacoesCount: 7,
    metaAgendamentos: 15,
    metaEfetivacaoRate: 50,
    active: true,
    admissionDate: '2025-01-20',
    team: 'Equipe Delta',
  },
  {
    id: 'sdr-5',
    name: 'Eduardo Santos',
    agendamentosCount: 10,
    efetivacoesCount: 3,
    metaAgendamentos: 15,
    metaEfetivacaoRate: 40,
    active: false,
    admissionDate: '2025-02-15',
    team: 'Equipe Beta',
  }
];

export const INITIAL_ASSESSORES: Assessor[] = [
  {
    id: 'assr-1',
    name: 'Mariana Lima (Ápice Invest)',
    active: true,
    agendaLink: 'https://calendly.com/mariana-lima-apice',
    exclusiveSdrId: '',
    participatesInRotation: true,
    team: 'Equipe Alpha',
  },
  {
    id: 'assr-2',
    name: 'Rodrigo Mello (Sul Capital)',
    active: true,
    agendaLink: 'https://calendly.com/rodrigo-mello',
    exclusiveSdrId: '',
    participatesInRotation: true,
    team: 'Equipe Beta',
  },
  {
    id: 'assr-3',
    name: 'Fernanda Albuquerque (Solidez)',
    active: true,
    agendaLink: 'https://calendly.com/fernanda-albuquerque',
    exclusiveSdrId: '',
    participatesInRotation: true,
    team: 'Equipe Delta',
  },
  {
    id: 'assr-4',
    name: 'Gabriel Rezende (Forte)',
    active: false,
    agendaLink: '',
    exclusiveSdrId: '',
    participatesInRotation: false,
    team: 'Equipe Beta',
  },
  {
    id: 'assr-5',
    name: 'Priscila Nogueira (Horizonte)',
    active: true,
    agendaLink: 'https://calendly.com/priscila-nogueira',
    exclusiveSdrId: 'sdr-1', // Exclusive to Ana Silva
    participatesInRotation: false,
    team: 'Equipe Alpha',
  },
  {
    id: 'assr-6',
    name: 'Thiago Martins (Vanguard)',
    active: true,
    agendaLink: 'https://calendly.com/thiago-vanguard',
    exclusiveSdrId: '',
    participatesInRotation: true,
    team: 'Equipe Delta',
  }
];
